# Generated by Django 5.0.2 on 2024-02-19 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0002_alter_speciality_institute'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='institute',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='practices', to='institutes.institute'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doclink',
            name='practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_links', to='partners.practice'),
        ),
        migrations.AlterField(
            model_name='parnter',
            name='image',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='practice',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practices', to='partners.parnter'),
        ),
    ]
