# Generated by Django 5.0.2 on 2024-02-19 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_practice_institute_alter_doclink_practice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_topics', to='partners.practice')),
            ],
        ),
    ]
