# Generated by Django 5.0.2 on 2024-02-19 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_practicetopic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='name',
        ),
    ]
